import Vue from "vue/dist/vue.js";

import UiAnimateDisplay from "./ui-animations/ui-animation-display.vue";
Vue.component("ui-animation-display", UiAnimateDisplay);
import UiWindow from "./ui-window/ui-window.vue";
Vue.component("ui-window", UiWindow);
import UiWindowCard from "./ui-window/ui-window-card.vue";
Vue.component("ui-window-card", UiWindowCard);
import UiBlind from "./ui-blind/ui-blind.vue";
Vue.component("ui-blind", UiBlind);
import UiButtonFile from "./ui-button/ui-button-file.vue";
Vue.component("ui-button-file", UiButtonFile);
import UiSpinner from "./ui-spinner/ui-spinner.vue";
Vue.component("ui-spinner", UiSpinner);
import UiMenu from "./ui-menu/ui-menu.vue";
Vue.component("ui-menu", UiMenu);
import UiBadge from "./ui-badge/ui-badge.vue";
Vue.component("ui-badge", UiBadge);
import UiSnackbar from "./ui-snackbar/ui-snackbar.vue";
Vue.component("ui-snackbar", UiSnackbar);
import UiImg from "./ui-img/ui-img.vue";
Vue.component("ui-img", UiImg);
import UiTabs from "./ui-tabs/ui-tabs.vue";
Vue.component("ui-tabs", UiTabs);
import UiTabsTab from "./ui-tabs/ui-tabs-tab.vue";
Vue.component("ui-tabs-tab", UiTabsTab);
import UiClickFeedback from "./ui-click-feedback/ui-click-feedback.vue";
Vue.component("ui-click-feedback", UiClickFeedback);

import UiTable from "./ui-table/ui-table.vue";
Vue.component("ui-table", UiTable);
import UiTableBody from "./ui-table/ui-table-body.vue";
Vue.component("ui-table-body", UiTableBody);
import UiTableHeader from "./ui-table/ui-table-header.vue";
Vue.component("ui-table-header", UiTableHeader);
import UiTableTd from "./ui-table/ui-table-td.vue";
Vue.component("ui-table-td", UiTableTd);
import UiTableTh from "./ui-table/ui-table-th.vue";
Vue.component("ui-table-th", UiTableTh);
import UiTableTr from "./ui-table/ui-table-tr.vue";
Vue.component("ui-table-tr", UiTableTr);
import UiTableSpan from "./ui-table/ui-table-span.vue";
Vue.component("ui-table-span", UiTableSpan);

//элементы формы
import UiEfText from "./ui-element-form/ui-ef-text.vue";
Vue.component("ui-ef-text", UiEfText);
import UiEfTextarea from "./ui-element-form/ui-ef-textarea.vue";
Vue.component("ui-ef-textarea", UiEfTextarea);
import UiEfPhone from "./ui-element-form/ui-ef-phone.vue";
Vue.component("ui-ef-phone", UiEfPhone);
import UiEfPassword from "./ui-element-form/ui-ef-password.vue";
Vue.component("ui-ef-password", UiEfPassword);
import UiEfDatePicker from "./ui-element-form/ui-ef-datepicker.vue";
Vue.component("ui-ef-datepicker", UiEfDatePicker);
import UiEfSelect from "./ui-element-form/ui-ef-select.vue";
Vue.component("ui-ef-select", UiEfSelect);
import UiEfCheckbox from "./ui-element-form/ui-ef-checkbox.vue";
Vue.component("ui-ef-checkbox", UiEfCheckbox);
import UiEfSearch from "./ui-element-form/ui-ef-search.vue";
Vue.component("ui-ef-search", UiEfSearch);
import UiEfChips from "./ui-element-form/ui-ef-chips.vue";
Vue.component("ui-ef-chips", UiEfChips);
import UiEfContent from "./ui-element-form/ui-ef-content.vue";
Vue.component("ui-ef-content", UiEfContent);
import UiEfContainer from "./ui-element-form/ui-ef-container.vue";
Vue.component("ui-ef-container", UiEfContainer);
import UiEfRadio from "./ui-element-form/ui-ef-radio.vue";
Vue.component("ui-ef-radio", UiEfRadio);
import UiHelper from "./ui-helper/ui-helper.vue";
Vue.component("ui-helper", UiHelper);
